# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_statedist <- function(delta, Gamma) {
    .Call('_statedist_calc_statedist', PACKAGE = 'statedist', delta, Gamma)
}

